version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
