FROM python:3.11-slim

WORKDIR /app

# Copiar dependências
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY . .

# Expõe a porta que Django vai rodar
EXPOSE 8000

# Rodar servidor Gunicorn
CMD ["gunicorn", "backend-pokedex.wsgi:application", "--bind", "0.0.0.0:8000"]
