# Etapa 1: Build do Angular
FROM node:20-alpine AS build

WORKDIR /app

# Copia package.json e package-lock.json para instalar dependências
COPY package*.json ./
RUN npm install

# Copia todo o código
COPY . .

# Build para produção
RUN npm run build --prod

# Etapa 2: Servir com Nginx
FROM nginx:alpine

# Copia o build do Angular para o Nginx
COPY --from=build /app/dist/pokedex-frontend /usr/share/nginx/html

# Copia configuração customizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expõe porta 80
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
