# Generated by Django 5.2.7 on 2025-10-08 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id_tipo_pokemon', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('dt_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('id_pokemon_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('imagem_url', models.URLField()),
                ('grupo_batalha', models.BooleanField(default=False)),
                ('favorito', models.BooleanField(default=False)),
                ('tipos', models.ManyToManyField(related_name='pokemons', to='core.tipopokemon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='core.usuario')),
            ],
        ),
    ]
