# Generated by Django 5.2.7 on 2025-10-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_senha_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='geracao',
            field=models.IntegerField(default=1),
        ),
    ]
