# Generated by Django 5.2.7 on 2025-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pokemonusuario_geracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonusuario',
            name='stats_cache',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
