# Generated by Django 5.2.7 on 2025-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pokemonusuario_stats_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('imagem_url', models.URLField()),
                ('tipos', models.JSONField(default=list)),
                ('status', models.JSONField(default=list)),
                ('habilidades', models.JSONField(default=list)),
                ('movimentos', models.JSONField(default=list)),
                ('sprites', models.JSONField(default=list)),
                ('evolution_chain', models.JSONField(default=list)),
                ('geracao', models.IntegerField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
